#Common linux library for develop or it's precondition for running some apps

- name: Installing Python and its dependency
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python
    - python-dev
    - libxml2-dev
    - libxslt-dev
    - libssl-dev
    - libffi-dev
    - python-pip
  tags: python
- pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - urllib3 # require for install docker via ansible galaxy if python's version >= 2.7.9
    - pyopenssl # require for install docker via ansible galaxy if python's version >= 2.7.9
    - ndg-httpsclient # require for install docker via ansible galaxy if python's version >= 2.7.9
    - pyasn1 # require for install docker via ansible galaxy if python's version >= 2.6
  tags: python