- hosts: localhost
  remote_user: hoan
  become: true
  roles:
    - role: vms
      tags: vms

    # devops tools
    - role: dochang.docker
      docker_users: hoan
      tags: docker

#  tasks:
#    - name: nan;a
#    TODO

