- hosts: devops
  remote_user: hoan
  become: true
  roles:
    - role: vms
      tags: vms

    # devops tools
    - role: dochang.docker
      docker_users: hoan
      tags: docker

  tasks:
    - name: Make sure groovy lib was existed
      get_url:
        url: "https://dl.bintray.com/groovy/maven/apache-groovy-binary-{{ groovy_version }}.zip"
        dest: "{{ extract_to_path }}"
      tags: groovy
    - unarchive:
        src: "{{ extract_to_path }}/apache-groovy-binary-{{ groovy_version }}.zip"
        dest: "{{ extract_to_path }}"
      tags: groovy

