- hosts: docker
  remote_user: vagrant
  become: yes

#  pre_tasks:
#    - name: Make sure secret file was copy to ~/.ssh
#      pause:
#        prompt: |+
#            # TODO: 1->4 can be automated if store keys locally
#            - 1. ssh-copy-id -i {path to public key } username@hostname
#            - 2. enter password when require
  roles:
    - unix-dev-lib
    - dochang.docker
    - jenkins
    - jenkins-slave