---
 - hosts: localhost
   remote_user: hoan
   become: true
   pre_tasks:
    - name: Cleaning cache
      command: apt-get clean

   roles:
      - role: common-tools
        tags: common-tools

      # devops tools
      - role: dochang.docker
        docker_users: hoan
        tags: docker
