---
 - name: Create default directory
   file:
     path: "{{ item.dir }}"
     mode: "{{ item.mode }}"
     state: directory
     recuse: yes
   with_items:
    "{{ configs_dir }}"

 - name: Install Unikey for Ubuntu
   apt:
     name: ibus-unikey
     state: latest
#     update_cache: yes
   tags: install_all, necessary_app

 - name: Installing OpenJDK
   apt:
     name: openjdk-8-jdk
   tags: install_all, necessary_app

 - name: Installing Filezilla
   apt:
     name: filezilla
   tags: install_all, necessary_app

 - name: Installing VirtualBox (latest version)
   apt:
     name: virtualbox
   tags: install_all, necessary_app

 - name: Installing Virtualbox extension package
   apt:
     name: virtualbox-ext-pack
   tags: install_all, necessary_app

# - name: Installing Skype
#   apt:
#     deb: https://download.skype.com/linux/skype-ubuntu-precise_4.3.0.37-1_i386.deb
#   tags: install_all, necessary_app
#
# - name: Installing Teamview
#   apt:
#     deb: https://download.teamviewer.com/download/teamviewer_i386.deb
#   tags: install_all, necessary_app

 - name: Installing Git version control
   apt:
      name: git
   tags: install_all, necessary_app

 - name: Installing NodeJS (Step 1)
   shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
   tags: install_all, necessary_app, nodejs

 - name: Installing NodeJS (Step 2)
   apt:
     name: nodejs
     state: latest
   tags: install_all, necessary_app, nodejs

 - name: Install Java JDK (OpenJDK-8)
   apt:
     name: openjdk-8-jdk
   tags: install_all, necessary_app

